openapi: 3.0.3
info:
  title: Sample API
  description: A short description of API.
  termsOfService: http://example.com/terms/
  contact:
    name: API support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server

paths:

  /users/{userId}:
    get:
      tags:
        - users
      summary: Get user by ID.
      description: Returns a single User model
      operationId: GetUserByID
      parameters:
        - name: userId
          in: path
          description: user id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single User model
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
                example:
                  id: 1
                  name: John Doe

  /tweets/{tweetId}:
    get:
      tags:
        - tweets
      summary: Get tweet by ID.
      description: Returns a single Tweet model
      operationId: GetTweetByID
      parameters:
        - name: tweetId
          in: path
          description: tweet id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single Tweet model
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Tweet'
                example:
                  id: 1
                  text: John Doe
                  user_id: 1


components:
  schemas:
    User:
      type: object
      required:
        - id
      properties:
        id:
          type: integer 
          format: int64
        name:
          type: string

    Tweet:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        user_id:
          type: integer
          format: int64

security: 
  # Non-OAuth setting
  - api_key: []
  # OAuth setting
  - users_auth:
    - write:users
    - read:users

tags:
  - name: users
    description: Access to Users
  - name: tweets
    description: Access to Tweets

externalDocs:
  description: Find more info here
  url: https://example.com
